# Spécifie la version de l'API CircleCI à utiliser
version: 2.1

# Définit les workflows qui seront exécutés dans CircleCI
workflows:
  # Configuration du workflow pour la branche master
  version: 2.1
  build_and_test:
    jobs:
      # Configuration du job de build et de test
      - build_and_test:
          filters:
            branches:
              only: master

# Définit les jobs qui seront exécutés dans le workflow
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn jacoco:report
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t a09da491-4dc1-4596-8c54-a4463e6a571b
  # Configuration du job de build et de test
  build_and_test:
    # Définit l'environnement pour le job
    docker:
      - image: cimg/openjdk:17.0.1
    # Définit les étapes à exécuter pour le job
    steps:
      # Récupère le code source depuis GitHub
      - checkout
      # Installe les dépendances du projet
      - run: mvn dependency:go-offline
      # Exécute les tests unitaires
      - run: mvn clean test